### ISSUE TITLE
Change password link on login screen, unresponsive

### ISSUE THREAD

**Issue by championballer** [fossasia/susi_chromebot#334] opened 2018-09-23 05:25 UTC
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
There is text "Change password" on the login portal that seems out of place and is also unresponsive

**Expected behavior:**
It should not be there. It should come up when the user clicks on forgot password.

**Steps to reproduce:**
open login.html in src folder of susi_chromebot

**Related code:**
                        <a  style="margin-left:35%; color:#fff;"  id="pass" href="#" >Click here to change password</a>

**Would you like to work on the issue?**

Yes

**Comment by gabru-md** [comment] 2018-09-23 05:37
Asigned to you :)

**Comment by rupav** [comment] 2018-09-23 06:10
It should be there @championballer if the user is logged in. Its responsive for me. Just checked. Please post a screenshot of your problem.

**Comment by championballer** [comment] 2018-09-23 06:27
![change password](https://user-images.githubusercontent.com/39242078/45924855-dbf9a180-bf27-11e8-9d0c-26bc801e9b11.png)

Should it be on the login portal @rupav

**Comment by rupav** [comment] 2018-09-23 06:40
I still cant get to this page. Please state `steps to reproduce this form`.

**Comment by championballer** [comment] 2018-09-23 06:43
@rupav, I just opened the login.html file after cloning the repo. this morning.

**Comment by rupav** [comment] 2018-09-23 06:52
Ok 👍. I am unable to reproduce this issue on my side. I would recommend you to start working on it after PR 319 gets merged, and you can then pull the changes in your local repo. Then try again reproducing this error.

**Closed** 2018-09-23 08:17 UTC
